-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:662a7dde464180409e6923801d6466d4$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "tile_A_0001.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 42, y = 156, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0002.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 4, y = 194, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0500.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 4, y = 156, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0501.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 80, y = 118, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0502.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 42, y = 118, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0503.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 4, y = 118, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0504.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 80, y = 80, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0505.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 42, y = 80, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0530.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 4, y = 4, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0550.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 4, y = 80, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0551.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 80, y = 42, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0552.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 42, y = 42, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0553.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 4, y = 42, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0554.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 80, y = 4, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0555.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 42, y = 4, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

